# Generated by Django 4.0.3 on 2022-06-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
    ]
