# Generated by Django 4.0.3 on 2022-06-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(blank=True, max_length=25, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.CharField(blank=True, max_length=25, verbose_name='Quantity'),
        ),
    ]
